name: Build, Test, and Publish VSCode Extension
on:
  push:
    branches:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3.8.1
  #       with:
  #         node-version: lts/*
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build the extension
  #       run: npm run vscode:prepublish

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3.8.1
  #       with:
  #         node-version: lts/*
  #         cache: npm
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run Pre Test
  #       run: npm run pretest
  #     - name: Run Tests
  #       uses: GabrielBB/xvfb-action@v1.6
  #       with:
  #         run: npm test
  publish:
    # needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Package For Marketplace
        run: npm run vsce-package
      - name: Set Git Config
        run: |
          git config user.name "Phil Daniels"
          git config user.email "phil@danielsdev.cloud"

      - name: Set Git Credentials
        run: |
          git config --global credential.helper store
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch
      - name: Publish to VSCode Marketplace
        env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
        run: npm run vsce-publish:ci:minor
