name: Bump Major Version
on:
  push:
    branches:
      - 'release/*'
jobs:
  bump_major:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set Git Config
        run: |
          git config user.name "Phil Daniels"
          git config user.email "phil@danielsdev.cloud"
      - name: Set Git Credentials
        run: |
          git config --global credential.helper store
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch
      - name: Bump major version
        run: |
          git pull
          npm version major
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
