name: Bump Minor Version
on:
  push:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set Git Config
        run: |
          git config user.name "Phil Daniels"
          git config user.email "phil@danielsdev.cloud"
      - name: Set Git Credentials
        run: |
          git config --global credential.helper store
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch
      - name: Run npm version minor
        run: |
          git pull
          npm version minor
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
